# Options for analysis running.
run:
  timeout: 2m
  skip-dirs:
    - tmpmod
linters:
  fast: false
  enable:
    - misspell
    - gosec
    - godot
    - revive
    - errorlint
linters-settings:
  errcheck:
    check-type-assertions: true
  misspell:
    locale: US
    ignore-words: []
  revive:
    rules:
      - name: unexported-return
        disabled: true
      - name: exported
        disabled: false
