before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  -
    id: runn-darwin
    ldflags:
      - -s -w -X github.com/k1LoW/runn.version={{.Version}} -X github.com/k1LoW/runn.commit={{.FullCommit}} -X github.com/k1LoW/runn.date={{.Date}} -X github.com/k1LoW/runn/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/runn/main.go
  -
    id: runn-linux
    ldflags:
      - -s -w -X github.com/k1LoW/runn.version={{.Version}} -X github.com/k1LoW/runn.commit={{.FullCommit}} -X github.com/k1LoW/runn.date={{.Date}} -X github.com/k1LoW/runn/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/runn/main.go
archives:
  -
    id: runn-archive
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: darwin
        format: zip
    files:
      - CREDITS
      - README.md
      - CHANGELOG.md
    rlcp: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: runn-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - runn-linux
    homepage: https://github.com/k1LoW/runn
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: runn is a tool for running operations following a scenario.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1
