name: Rerun flaky jobs

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  rerun:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    permissions:
      contents: read
      actions: write
    steps:
      - uses: k1LoW/rerun-action@80c58dc1309b82e2746743ea0dc3f726313412a1 # v1.2.0
        with:
          run_id: ${{ github.event.workflow_run.id }}
          pattern: 'Check failed: ThreadCache::IsValid'
          job: |
            Test
            Check race
          max_attempts: 10
