name: Rerun flaky jobs

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  rerun:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    permissions:
      contents: read
      actions: write
    steps:
      - uses: k1LoW/rerun-action@182a20f04ea316e2d26b11a66839c275ad301562 # v1.1.0
        with:
          run_id: ${{ github.event.workflow_run.id }}
          pattern: 'Check failed: ThreadCache::IsValid'
          job: |
            Test
            Check race
          max_attempts: 3
